import cProfile
import pstats
import io
from pstats import SortKey

from asgn_4_package.lib_raw import StringAnalysis


def test_profile_main():
    # Sample DNA sequences for benchmarking
    data_1 = "gtctgggagtctagataagtaaccgcgacggatcaaatttgtgcggcggtacataacctgagttcctatggtgagggatccgcttttcacttgaggagctattctaaagttccgcggctctacacgtgcccgtctaaaaaaacaaaagtcacgctacatctagcaagaacagagttcatatggactgctgacttatatagccaagtcaccggtttcaccacgatgtatacgttgtcgggtcgaaatgtggttaggactcttgcgctaatgatccaataagctttggtccccggttcgagctgccgaggaaggcgggccaaaacatcccgggaacgcgattctgctctacacacagcatgactgtcccaaataagatcctccgacggcgtccccatgacggattcatctagttgacggccaacggactccccagcgtgggagatgtaagaaacgcagatcctaggagactaccatgctcttaaggcggtactcaggcacgtccacattatctaagcgttcgatcggtaaccgattagagcgacaggattcaaccgtgaaaagctaactaggatggccggcaaatgcaggtgcgggcaggtcaagagataataaaagtgggtcttcgctgcgtcttgtagggtgctggggcgagtattagtcactacagataagttttgcggatggcgaaggggggggctaaacttcgcagtagctcccgaacgtcagtctcgtcttgcgccctcagtcaaggccggctccattggcgggtctcagggggctcggggtatttcatatcaaggccctagcatgatatccagagcaataggtcgcaggctgcaaatgaagggataaatggtccgagaggcgctcctaatagatttgggggatgacgatacgggtgaggtcatataggagctagtgccaacgaaagttcctattgtgcccttgatcgaggtgctatgttacacagtagtaaacgagcggtcctcagtttttgactaaaatcggacggctcgaatggactctctgaccggttggtggaacccggtgccagattactggtagattttgtatcggttcaaacgatcgacggcgcaattcacatgccgatatgcctatccccccaggatcctggtaaggaatcaatccaagactacgatgttgcagagggtattttgtccgctacgctttccagccgtagggcacggtccacagatttccgcgatggaaaaatcgccagccttttatgttatcgcactggaataagattaccgttggatcggactgcttcatccctgacttgcgattcgctacaaagaactgcacaacgcacctcctatactcgtacctgtaggtggatcaagtatctttatgtcgcgattaaattgcctcgtcatggatggtactcggcaccgggaaggtttggatatgcctgcacttcacagaggttagggttcctgactcgcggcataccttaaccccgggctcttctaggtggtacggggcacagccgaaaaaaaaaggtcgtctggcctcatcaaataaccaaccacaactgtccacctaattccctgacagcttagccatctaactttccgaagtcaaccagtacgcaattatttaccgcgcatgtctcgcgtagccggcggtaacgatgttggtggtgttctcgctgacaagagtcctaaggaggcgacacaattatgtttcggattgtcacgtctcatattcacctcactccataagaactacccagctactttttctggacccgtcgctaaggaatcgaagatagtgcggattcgtcaatgcatacgtgataatttggtccgggcggtcatacgtactgacacgacgtgggtagattgcgtccagtatgcatcaaaattcgatcgaggagtggtgtccatgggcggatagggatttcaaaccgtaactatctttagctggccagattaccatagggcggagtggtggagtggggagagctagtcagtggt"
    data_2 = "gtctgggagtctagataagtaaccgcgacggatcaaatttgtgcggcggtacataacctgagttcctatggtgagggatccgcttttcacttgaggagctattctaaagttccgcggctctacacgtgcccgtctaaaaaaacaaaagtcacgctacatctagcaagaacagagttcatatggactgctgacttatatagccaagtcaccggtttcaccacgatgtatacgttgtcgggtcgaaatgtggttaggactcttgcgctaatgatccaataagctttggtccccggttcgagctgccgaggaaggcgggccaaaacatcccgggaacgcgattctgctctacacacagcatgactgtcccaaataagatcctccgacggcgtccccatgacggattcatctagttgacggccaacggactccccagcgtgggagatgtaagaaacgcagatcctaggagactaccatgctcttaaggcggtactcaggcacgtccacattatctaagcgttcgatcggtaaccgattagagcgacaggattcaaccgtgaaaagctaactaggatggccggcaaatgcaggtgcgggcaggtcaagagataataaaagtgggtcttcgctgcgtcttgtagggtgctggggcgagtattagtcactacagataagttttgcggatggcgaaggggggggctaaacttcgcagtagctcccgaacgtcagtctcgtcttgcgccctcagtcaaggccggctccattggcgggtctcagggggctcggggtatttcatatcaaggccctagcatgatatccagagcaataggtcgcaggctgcaaatgaagggataaatggtccgagaggcgctcctaatagatttgggggatgacgatacgggtgaggtcatataggagctagtgccaacgaaagttcctattgtgcccttgatcgaggtgctatgttacacagtagtaaacgagcggtcctcagtttttgactaaaatcggacggctcgaatggactctctgaccggttggtggaacccggtgccagattactggtagattttgtatcggttcaaacgatcgacggcgcaattcacatgccgatatgcctatccccccaggatcctggtaaggaatcaatccaagactacgatgttgcagagggtattttgtccgctacgctttccagccgtagggcacggtccacagatttccgcgatggaaaaatcgccagccttttatgttatcgcactggaataagattaccgttggatcggactgcttcatccctgacttgcgattcgctacaaagaactgcacaacgcacctcctatactcgtacctgtaggtggatcaagtatctttatgtcgcgattaaattgcctcgtcatggatggtactcggcaccgggaaggtttggatatgcctgcacttcacagaggttagggttcctgactcgcggcataccttaaccccgggctcttctaggtggtacggggcacagccgaaaaaaaaaggtcgtctggcctcatcaaataaccaaccacaactgtccacctaattccctgacagcttagccatctaactttccgaagtcaaccagtacgcaattatttaccgcgcatgtctcgcgtagccggcggtaacgatgttggtggtgttctcgctgacaagagtcctaaggaggcgacacaattatgtttcggattgtcacgtctcatattcacctcactccataagaactacccagctactttttctggacccgtcgctaaggaatcgaagatagtgcggattcgtcaatgcatacgtgataatttggtccgggcggtcatacgtactgacacgacgtgggtagattgcgtccagtatgcatcaaaattcgatcgaggagtggtgtccatgggcggatagggatttcaaaccgtaactatctttagctggccagattaccatagggcggagtggtggagtggggagagctagtcagtggt"
    
    pr = cProfile.Profile()
    
    # Create analyzer instance
    analyzer = StringAnalysis(data_1, data_2)
    
    # Profile the analyze method
    pr.runcall(analyzer.analyze)
    
    pr.disable()

    s = io.StringIO()
    sortby = SortKey.CUMULATIVE
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print(s.getvalue())


if __name__ == "__main__":
    test_profile_main()
